package nautictracker;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nautictracker.Trip;
import nautictracker.TrackPoint;

import nautictracker.TripDao;
import nautictracker.TrackPointDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tripDaoConfig;
    private final DaoConfig trackPointDaoConfig;

    private final TripDao tripDao;
    private final TrackPointDao trackPointDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tripDaoConfig = daoConfigMap.get(TripDao.class).clone();
        tripDaoConfig.initIdentityScope(type);

        trackPointDaoConfig = daoConfigMap.get(TrackPointDao.class).clone();
        trackPointDaoConfig.initIdentityScope(type);

        tripDao = new TripDao(tripDaoConfig, this);
        trackPointDao = new TrackPointDao(trackPointDaoConfig, this);

        registerDao(Trip.class, tripDao);
        registerDao(TrackPoint.class, trackPointDao);
    }
    
    public void clear() {
        tripDaoConfig.getIdentityScope().clear();
        trackPointDaoConfig.getIdentityScope().clear();
    }

    public TripDao getTripDao() {
        return tripDao;
    }

    public TrackPointDao getTrackPointDao() {
        return trackPointDao;
    }

}
