package nautictracker;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRIP.
 */
public class Trip {

    private Long id;
    private Long remote_id;
    private String title;
    private Boolean saved;

    public Trip() {
    }

    public Trip(Long id) {
        this.id = id;
    }

    public Trip(Long id, Long remote_id, String title, Boolean saved) {
        this.id = id;
        this.remote_id = remote_id;
        this.title = title;
        this.saved = saved;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRemote_id() {
        return remote_id;
    }

    public void setRemote_id(Long remote_id) {
        this.remote_id = remote_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean getSaved() {
        return saved;
    }

    public void setSaved(Boolean saved) {
        this.saved = saved;
    }

}
